### PR TITLE
Modernize styleeditor

### PR DESCRIPTION
**Pull request by janbar**
This is the proposal on my rework of the tool to edit style sheet. The target is to modernize the GUI tool, improve performances, and make it work with Qt5.15 and Qt6.

The new one:
Capture d’écran du 2024-08-30 13-46-38

I fixed some performance issues with the editor and the gui. It implements natively the block indentation, and the editing is smooth with the style analyser.

The customized shortcuts are:
- Ctrl+S: Save
- Ctrl+C: Copy selected block
- Ctrl+X: Cut selected block
- Ctrl+V: Paste
- Ctrl+F : focus the search text input
- F3: Find next
- Shift+F3: Find previous
- PageDown: move cursor to next page
- PageUp: move cursor to previous page
- Tab: insert indent or indent+ selected block
- Shift+Tab: indent- selected block

### CODE REVIEW

**Comment by janbar** [comment]
At this stage the thing works. It still to reconnect the "StyleAnalyser", to review the license header of source files, and probably a final cleanup.

@Karry , do you have any suggestions ?

**Comment by janbar** [comment]
@Framstag , the work is finished.

**Comment by janbar** [comment]
Please see PR #1591. I will rebase this after the resolution.

**Comment by Framstag** [comment]
@janbar : Somehwere in between you claimed to be finished, but you are obviously not ;-) Please signal again, if you are finished.

**Comment by janbar** [comment]
@Framstag , it is finished and refine ;-). But it works only with the PR #1591, else the analyser will crash the app. So I rebase it now without including the fix #1591. And let you merge it if you approve it !

**Pull request merged**
