### PR TITLE
TransPolygon should generate simple way/area

### PR DESCRIPTION
**Pull request by Karry**
work in progress... I want to fix https://github.com/Framstag/libosmscout/issues/282

* add test (currently broken) that TransPolygon generates simple way/area

### CODE REVIEW

**Comment by Framstag** [comment]
Hello Karry: You need to update the branch before I can merge. If you have added a test that fails, why does the build not break?

**Comment by Karry** [comment]
> why does the build not break?

Because this test was not in "checked tests" that are running as part of the build. Build should be failing now, after rebase...

**Comment by Karry** [comment]
Hi, it should be working. I enforce simple coastlines in WaterIndexGenerator, and it fixes this issue: https://github.com/Framstag/libosmscout/issues/282

WaterIndexGenerator is little bit slower now, `FindIntersection` method is not optimized well...

**Comment by Framstag** [comment]
I haven't check the code for correctness, but regarding performance there are some possible change you should check.  Also instead of a bool parameter an enum might be more suited.

Nevertheless: Thanks for taking a look!

**Comment by Framstag** [comment]
Is the patch for the added Test still necessary? Looks like it is included here, too?

**Comment by Karry** [comment]
Sorry, what Test do you mean?

**Comment by Karry** [comment]
To performance of searching path intersection, it can be improved in the future. I wrote similar method here: https://github.com/Framstag/libosmscout/pull/190/files#diff-d0db01360850c3c8acce2050fc081f31R266 and it is much faster. It may be generalised and used on both places...

**Comment by Framstag** [comment]
There was a pill request named "Test" yesterday, but it now has disappeared. Perhaps I missed a refresh in GitHub.

**Comment by Karry** [comment]
You merged it already: https://github.com/Framstag/libosmscout/pull/289 I just rebase this one against master...

**Comment by Framstag** [comment]
I did start a GitHub review but just have seen, that it was not finished :-/ I finished it now. Did you get my comments already earlier or just now?

**Comment by Karry** [comment]
I see review comments when it is finished. Not before.

I added (const) references, it is better. But how should I replace `bool requireSimple`? Should I additional flags? Or just enum like this:
```
enum OutputRequirements
{
  none = 0,
  simple = 1
}
```

**Comment by Framstag** [comment]
regarding visibility of comments: OK.

Regarding RequireSimple: Yes I suggest using an enum. For toggles that are not obviously of boolean character, using an enum create IMHo a better API. It also makes call to the method easier to grasp.

**Comment by Karry** [comment]
Ok, updated. I add `OutputConstraint` enum...

**Comment by Framstag** [comment]
Ok.  Can you make a new issue for your suggested optimization.

**Pull request merged**
