### PR TITLE
Continue work on CMake

### PR DESCRIPTION
**Pull request by OgreTransporter**
Continue working on PR #899

### CODE REVIEW

**Comment by Framstag** [comment]
@OgreTransporter I'm rather busy this weekend, but if you need further analysis regarding your patch just give me a hint.

**Comment by Framstag** [comment]
I have canceled older appveyor builds. Appveyor does make a separate build for each checking for the same patch. Have to check, if this can be changed :-/

**Comment by OgreTransporter** [comment]
Unfortunately I cannot understand the CI problem https://travis-ci.com/github/Framstag/libosmscout/jobs/393012721. I have installed Ubuntu and entered the following commands:
```
git clone -b rework-cmake https://github.com/OgreTransporter/libosmscout.git
mkdir build
cd build
cmake ../libosmscout/
make
```
Result: Works.

**Comment by Framstag** [comment]
This is the script that gets executed: https://github.com/Framstag/libosmscout/blob/master/ci/travis/build.sh

with TARGET=importer

which means that in the end https://github.com/Framstag/libosmscout/blob/master/packaging/import/linux/build_import.sh is executed. The most likely option to trigger the failure is

-DBUILD_SHARED_LIBS=OFF

In above example you likely build with shared linkage. The failing project tries to build a "statically linked, runs on every linux distribution" version of the installer.

Does that help?

**Comment by Karry** [comment]
I believe that main issue with static Importer is removal of this condition: https://github.com/Framstag/libosmscout/pull/899/files#diff-af3b638bc2a3e6c650974192a53c7291L163
```
# prefer static libraries if making import tool
if(BUILD_IMPORT_TOOL_FOR_DISTRIBUTION AND (CMAKE_COMPILER_IS_GNUCXX OR CMAKE_COMPILER_IS_CLANGXX OR CMAKE_COMPILER_IS_GNUCC))
  SET(CMAKE_FIND_LIBRARY_SUFFIXES .a ${CMAKE_FIND_LIBRARY_SUFFIXES})
endif()
```
see this MR: https://github.com/Framstag/libosmscout/pull/930

**Comment by OgreTransporter** [comment]
@Karry Many thanks for the tip! Now the CI should work completely again.

**Comment by OgreTransporter** [comment]
```
git clone -b rework-cmake https://github.com/OgreTransporter/libosmscout.git
mkdir build
cd build
cmake cmake \
    -DBUILD_SHARED_LIBS=OFF \
    -DCMAKE_LINK_SEARCH_END_STATIC=ON \
    -DCMAKE_LINK_SEARCH_START_STATIC=ON \
    -DCMAKE_BUILD_TYPE=Release \
    -DOSMSCOUT_BUILD_MAP_OPENGL=OFF \
    -DOSMSCOUT_BUILD_MAP_AGG=OFF \
    -DOSMSCOUT_BUILD_MAP_CAIRO=OFF \
    -DOSMSCOUT_BUILD_MAP_QT=OFF \
    -DOSMSCOUT_BUILD_MAP_SVG=OFF \
    -DOSMSCOUT_BUILD_MAP_IOSX=OFF \
    -DOSMSCOUT_BUILD_TESTS=OFF \
    -DOSMSCOUT_BUILD_DEMOS=OFF \
    -DOSMSCOUT_BUILD_BINDING_JAVA=OFF \
    -DOSMSCOUT_BUILD_BINDING_CSHARP=OFF \
    -DOSMSCOUT_BUILD_DOC_API=OFF \
    -DOSMSCOUT_BUILD_TOOL_OSMSCOUT2=OFF \
    -DOSMSCOUT_BUILD_TOOL_STYLEEDITOR=OFF \
    -DGPERFTOOLS_USAGE=OFF \
    -DOSMSCOUT_BUILD_TOOL_DUMPDATA=OFF \
    -DOSMSCOUT_BUILD_CLIENT_QT=OFF \
    -DOSMSCOUT_BUILD_TOOL_IMPORT=ON \
    -DOSMSCOUT_BUILD_IMPORT=ON \
    -DOSMSCOUT_BUILD_WITH_OPENMP=OFF \
    -DOSMSCOUT_BUILD_IMPORT_TOOL_FOR_DISTRIBUTION=ON \
    ../libosmscout/
make
```
Result:
```
Scanning dependencies of target Import
[ 96%] Building CXX object Import/CMakeFiles/Import.dir/src/Import.cpp.o
[ 97%] Linking CXX executable Import
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libicuuc.a(putil.ao): In Funktion »uprv_dl_open_60«:
(.text+0x1d62): Warnung: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/lib/x86_64-linux-gnu/libxml2.a(nanohttp.o): In Funktion »xmlNanoHTTPConnectHost«:
(.text+0x835): Warnung: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
(.text+0x904): Warnung: Using 'gethostbyname' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
[ 97%] Built target Import
Scanning dependencies of target BasemapImport
[ 97%] Building CXX object BasemapImport/CMakeFiles/BasemapImport.dir/src/BasemapImport.cpp.o
[ 98%] Linking CXX executable BasemapImport
[ 98%] Built target BasemapImport
Scanning dependencies of target PublicTransportMap
[ 99%] Building CXX object PublicTransportMap/CMakeFiles/PublicTransportMap.dir/src/PublicTransportMap.cpp.o
[100%] Linking CXX executable PublicTransportMap
[100%] Built target PublicTransportMap
```

**Comment by Framstag** [comment]
Since it looks good now I would like to say thanks to @OgreTransporter for "keep working on" and @Karry for his help! I do enjoy watching the libosmscout "community" :-)

**Comment by OgreTransporter** [comment]
All CI builds have been successfully completed.

**Comment by Framstag** [comment]
Jippeyyy!

**Comment by OgreTransporter** [comment]
Thanks a lot for your help!

**Pull request merged**
