### PR TITLE
Support for basemap rendering in DrawMap* demos

### PR DESCRIPTION
**Pull request by Karry**

### CODE REVIEW

**Comment by Karry** [comment]
@vyskocil I make base map rendering as separate rendering step and removed duplicate code from Qt and iOS MapPainters. Can you please verify that iOS painter is working correctly? Thank you!

**Comment by Framstag** [comment]
Build your patch under OS X. Looks ok to me and identical to the original rendering. Is this enough or dso need explicit base map rendering?

test

**Comment by Karry** [comment]
It would be great to test standard database with basemap. I am pretty sure that it will be fine, but I cannot test it...

**Comment by Framstag** [comment]
Hmmm, the current DrawMapOSX does not support basemap rendering - at least it does not have an option for it.

**Comment by Framstag** [comment]
I did port the demo to the new approach...

test

More helpful?

**Comment by Karry** [comment]
Definitely :-) You are free to merge it, together with your changes in OS X demo...

**Comment by vyskocil** [comment]
@Karry and @Framstag  just had time to also check it, thank you ! 
map

**Pull request merged**
