### PR TITLE
New label layouter

### PR DESCRIPTION
**Pull request by Karry**
Here is new label layouter that I introduced on mailing list few weeks before. It supports layouting of contour labels - backend have to provide method for splitting label to separate glyphs. Because of this, label api was changed and affects all backends. Currently, new api was implemented for all backends except **Direct X** and **iOSX**. I would appreciate help with these two backends, because I don't have configured environments for its testing...

This merge request should solve these issues: https://github.com/Framstag/libosmscout/issues/287 https://github.com/Framstag/libosmscout/issues/105

It also adds support for contour labels to SVG backend ;-)

### CODE REVIEW

**Comment by laarmen** [comment]
I'll have a look at the DirectX part once I return from vacations, on
Monday 😉

Le mer. 25 juil. 2018 à 08:10, Lukáš Karas <notifications@github.com> a
écrit :

**Comment by vyskocil** [comment]
I'll update the iOS/OSX backend

**Comment by vyskocil** [comment]
Adding `#include <array>`  in  `LabelLayouter.h`fix it

**Comment by Framstag** [comment]
Boys, I'm very happy to see, how Lucas work gets appreciated and the fast commitment from you to fix the open ends. Great :-)

Around half of the build fail though. @Lukas will you try to fix the builds? Do you need further help? Should the build works or does you patch actively breaks things so I have to merge it to allow others to fix it. I would of course like to avoid broken code, but if it helps...

I would ignore the mingw meson build, I do not know what is happening there, the problem was there before. Code did build locally for me and IMHO it looks like this could possibly a problem with the build image.

**Comment by Karry** [comment]
Thanks @laarmen and @vyskocil , I appreciate it! 

Just recapitulation what is necessary for backend implementation:

> On the painter, I just removed DrawContourLabel and GetTextDimension methods 
> and add three new: RegisterRegularLabel RegisterContourLabel and DrawLabels. 
> Abstract painter don't care about label layouting anymore, 
> it is responsibility of painter implementation. There is new templated 
> LabelLayouter that may be used for that, implementation of few methods have 
> to be provided for layouting:
> 
>  - Layout - provide implementation specific label object with evaluated
>    bounding rectangle for given text and style
>  - Label::ToGlyphs - split Label to vector of implementation specific glyphs
>  - Glyph::TopLeft, Glyph::Width and Glyph::Height
> 
> and for drawing:
> 
>  - DrawLabel - slightly modified current DrawLabel method
>  - DrawGlyphs - draw glyphs with given possition and angle

@Framstag wait for the iOSX and DirectX imlementations, I don't want to break master.

**Comment by vyskocil** [comment]
The Apple builds still fails because of missing `#include <array>` in `LabelLayouter.h`

**Comment by vyskocil** [comment]
Is it possible to contribute some code to the pull request ? If yes, how ?

**Comment by Karry** [comment]
you should be able to create merge request to my branch... or just post link to your brach here, I will merge it manually...

**Comment by vyskocil** [comment]
The Mac OSX target is still not building because the DrawmapOSX demo was already in the main branch and now it is twice in `Demos/CMakeLists.txt` : 
```
CMake Error at Demos/CMakeLists.txt:212 (add_executable):
  add_executable cannot create target "DrawMapOSX" because another target
  with the same name already exists.  The existing target is an executable
  created in source directory
  "/Users/travis/build/Framstag/libosmscout/Demos".  See documentation for
  policy CMP0002 for more details.
```

**Comment by Karry** [comment]
Thank you for notice. I merged Tim's master and resolve this issue.

**Comment by Framstag** [comment]
Just for book keeping, directX backend changes still missing?

**Comment by laarmen** [comment]
Yep. Sorry, my bad, but sadly there are other problems at work that take
precedence over this. I have to declare it up for grabs :-(

**Comment by Framstag** [comment]
I possibly look at the direct X code then next week. Some questions though:
* Can the API change get implemented with minor chances or do we need some major restructuring?
* I would try to fix code using VisualStudio cmake based Build and testing against DrawMapDirectX.
* I would possibly try to generate an import using msys to miniomize the VisualStudio dependencies.
* If in doubt, I would fullfil the API using empty implementations, breaking the backend.
* Is this OK, or are there any further things I need to know or have you a better approach or some more hints?
* When would you likelx find time to fix the backend if I do not fix it?

**Comment by Karry** [comment]
> Can the API change get implemented with minor chances or do we need some major restructuring?

The change is bigger, but no-op implementation that will fix the build is easy. Just override pure virtual methods and remove nonexistent.

**Comment by Karry** [comment]
Hi. I just installed VisualStudio 2017 in virtual computer and that seems that msvc compiler has some trouble with templates... Even SVG painter can be link. 
```
C:\WINDOWS\MapPainterSVG.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl osmscout::LabelLayouter<struct osmscout::MapPainterSVG::NativeGlyph,class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> >,class osmscout::MapPainterSVG>::LabelLayouter<struct osmscout::MapPainterSVG::NativeGlyph,class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> >,class osmscout::MapPainterSVG>(class osmscout::MapPainterSVG *)" (__imp_??0?$LabelLayouter@UNativeGlyph@MapPainterSVG@osmscout@@V?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@V23@@osmscout@@QEAA@PEAVMapPainterSVG@1@@Z) referenced in function "public: __cdecl osmscout::MapPainterSVG::MapPainterSVG(class std::shared_ptr<class osmscout::StyleConfig> const &)" (??0MapPainterSVG@osmscout@@QEAA@AEBV?$shared_ptr@VStyleConfig@osmscout@@@std@@@Z)
C:\WINDOWS\MapPainterSVG.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: void __cdecl osmscout::LabelLayouter<struct osmscout::MapPainterSVG::NativeGlyph,class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> >,class osmscout::MapPainterSVG>::SetViewport(struct osmscout::Rectangle<double>)" (__imp_?SetViewport@?$LabelLayouter@UNativeGlyph@MapPainterSVG@osmscout@@V?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@V23@@osmscout@@QEAAXU?$Rectangle@N@2@@Z) referenced in function "protected: virtual void __cdecl osmscout::MapPainterSVG::BeforeDrawing(class osmscout::StyleConfig const &,class osmscout::Projection const &,class osmscout::MapParameter const &,class osmscout::MapData const &)" (?BeforeDrawing@MapPainterSVG@osmscout@@MEAAXAEBVStyleConfig@2@AEBVProjection@2@AEBVMapParameter@2@AEBVMapData@2@@Z)
C:\WINDOWS\MapPainterSVG.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: void __cdecl osmscout::LabelLayouter<struct osmscout::MapPainterSVG::NativeGlyph,class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> >,class osmscout::MapPainterSVG>::SetLayoutOverlap(double)" (__imp_?SetLayoutOverlap@?$LabelLayouter@UNativeGlyph@MapPainterSVG@osmscout@@V?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@V23@@osmscout@@QEAAXN@Z) referenced in function "protected: virtual void __cdecl osmscout::MapPainterSVG::BeforeDrawing(class osmscout::StyleConfig const &,class osmscout::Projection const &,class osmscout::MapParameter const &,class osmscout::MapData const &)" (?BeforeDrawing@MapPainterSVG@osmscout@@MEAAXAEBVStyleConfig@2@AEBVProjection@2@AEBVMapParameter@2@AEBVMapData@2@@Z)
C:\WINDOWS\MapPainterSVG.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: void __cdecl osmscout::LabelLayouter<struct osmscout::MapPainterSVG::NativeGlyph,class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> >,class osmscout::MapPainterSVG>::Reset(void)" (__imp_?Reset@?$LabelLayouter@UNativeGlyph@MapPainterSVG@osmscout@@V?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@V23@@osmscout@@QEAAXXZ) referenced in function "protected: virtual void __cdecl osmscout::MapPainterSVG::DrawLabels(class osmscout::Projection const &,class osmscout::MapParameter const &,class osmscout::MapData const &)" (?DrawLabels@MapPainterSVG@osmscout@@MEAAXAEBVProjection@2@AEBVMapParameter@2@AEBVMapData@2@@Z)
C:\WINDOWS\MapPainterSVG.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: bool __cdecl osmscout::LabelLayouter<struct osmscout::MapPainterSVG::NativeGlyph,class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> >,class osmscout::MapPainterSVG>::IsOverlay(class osmscout::LabelData const &)" (__imp_?IsOverlay@?$LabelLayouter@UNativeGlyph@MapPainterSVG@osmscout@@V?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@V23@@osmscout@@QEAA_NAEBVLabelData@2@@Z) referenced in function "public: void __cdecl osmscout::LabelLayouter<struct osmscout::MapPainterSVG::NativeGlyph,class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> >,class osmscout::MapPainterSVG>::DrawLabels<class osmscout::MapPainterSVG>(class osmscout::Projection const &,class osmscout::MapParameter const &,class osmscout::MapPainterSVG *)" (??$DrawLabels@VMapPainterSVG@osmscout@@@?$LabelLayouter@UNativeGlyph@MapPainterSVG@osmscout@@V?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@V23@@osmscout@@QEAAXAEBVProjection@1@AEBVMapParameter@1@PEAVMapPainterSVG@1@@Z)
C:\WINDOWS\MapPainterSVG.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: void __cdecl osmscout::LabelLayouter<struct osmscout::MapPainterSVG::NativeGlyph,class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> >,class osmscout::MapPainterSVG>::Layout(void)" (__imp_?Layout@?$LabelLayouter@UNativeGlyph@MapPainterSVG@osmscout@@V?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@V23@@osmscout@@QEAAXXZ) referenced in function "protected: virtual void __cdecl osmscout::MapPainterSVG::DrawLabels(class osmscout::Projection const &,class osmscout::MapParameter const &,class osmscout::MapData const &)" (?DrawLabels@MapPainterSVG@osmscout@@MEAAXAEBVProjection@2@AEBVMapParameter@2@AEBVMapData@2@@Z)
C:\WINDOWS\MapPainterSVG.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: void __cdecl osmscout::LabelLayouter<struct osmscout::MapPainterSVG::NativeGlyph,class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> >,class osmscout::MapPainterSVG>::RegisterLabel(class osmscout::Projection const &,class osmscout::MapParameter const &,class osmscout::Vertex2D const &,class std::vector<class osmscout::LabelData,class std::allocator<class osmscout::LabelData> > const &,double)" (__imp_?RegisterLabel@?$LabelLayouter@UNativeGlyph@MapPainterSVG@osmscout@@V?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@V23@@osmscout@@QEAAXAEBVProjection@2@AEBVMapParameter@2@AEBVVertex2D@2@AEBV?$vector@VLabelData@osmscout@@V?$allocator@VLabelData@osmscout@@@std@@@std@@N@Z) referenced in function "protected: virtual void __cdecl osmscout::MapPainterSVG::RegisterRegularLabel(class osmscout::Projection const &,class osmscout::MapParameter const &,class std::vector<class osmscout::LabelData,class std::allocator<class osmscout::LabelData> > const &,class osmscout::Vertex2D const &,double)" (?RegisterRegularLabel@MapPainterSVG@osmscout@@MEAAXAEBVProjection@2@AEBVMapParameter@2@AEBV?$vector@VLabelData@osmscout@@V?$allocator@VLabelData@osmscout@@@std@@@std@@AEBVVertex2D@2@N@Z)
C:\WINDOWS\MapPainterSVG.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: void __cdecl osmscout::LabelLayouter<struct osmscout::MapPainterSVG::NativeGlyph,class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> >,class osmscout::MapPainterSVG>::RegisterContourLabel(class osmscout::Projection const &,class osmscout::MapParameter const &,class osmscout::PathLabelData const &,class osmscout::LabelPath const &)" (__imp_?RegisterContourLabel@?$LabelLayouter@UNativeGlyph@MapPainterSVG@osmscout@@V?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@V23@@osmscout@@QEAAXAEBVProjection@2@AEBVMapParameter@2@AEBVPathLabelData@2@AEBVLabelPath@2@@Z) referenced in function "protected: virtual void __cdecl osmscout::MapPainterSVG::RegisterContourLabel(class osmscout::Projection const &,class osmscout::MapParameter const &,class osmscout::PathLabelData const &,class osmscout::LabelPath const &)" (?RegisterContourLabel@MapPainterSVG@osmscout@@MEAAXAEBVProjection@2@AEBVMapParameter@2@AEBVPathLabelData@2@AEBVLabelPath@2@@Z)
C:\WINDOWS\MapPainterSVG.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: class std::vector<class osmscout::LabelInstance<struct osmscout::MapPainterSVG::NativeGlyph,class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > >,class std::allocator<class osmscout::LabelInstance<struct osmscout::MapPainterSVG::NativeGlyph,class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > > > > const & __cdecl osmscout::LabelLayouter<struct osmscout::MapPainterSVG::NativeGlyph,class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> >,class osmscout::MapPainterSVG>::Labels(void)const " (__imp_?Labels@?$LabelLayouter@UNativeGlyph@MapPainterSVG@osmscout@@V?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@V23@@osmscout@@QEBAAEBV?$vector@V?$LabelInstance@UNativeGlyph@MapPainterSVG@osmscout@@V?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@@osmscout@@V?$allocator@V?$LabelInstance@UNativeGlyph@MapPainterSVG@osmscout@@V?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@@osmscout@@@std@@@std@@XZ) referenced in function "public: void __cdecl osmscout::LabelLayouter<struct osmscout::MapPainterSVG::NativeGlyph,class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> >,class osmscout::MapPainterSVG>::DrawLabels<class osmscout::MapPainterSVG>(class osmscout::Projection const &,class osmscout::MapParameter const &,class osmscout::MapPainterSVG *)" (??$DrawLabels@VMapPainterSVG@osmscout@@@?$LabelLayouter@UNativeGlyph@MapPainterSVG@osmscout@@V?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@V23@@osmscout@@QEAAXAEBVProjection@1@AEBVMapParameter@1@PEAVMapPainterSVG@1@@Z)
C:\WINDOWS\MapPainterSVG.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: class std::vector<class osmscout::ContourLabel<struct osmscout::MapPainterSVG::NativeGlyph>,class std::allocator<class osmscout::ContourLabel<struct osmscout::MapPainterSVG::NativeGlyph> > > const & __cdecl osmscout::LabelLayouter<struct osmscout::MapPainterSVG::NativeGlyph,class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> >,class osmscout::MapPainterSVG>::ContourLabels(void)const " (__imp_?ContourLabels@?$LabelLayouter@UNativeGlyph@MapPainterSVG@osmscout@@V?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@V23@@osmscout@@QEBAAEBV?$vector@V?$ContourLabel@UNativeGlyph@MapPainterSVG@osmscout@@@osmscout@@V?$allocator@V?$ContourLabel@UNativeGlyph@MapPainterSVG@osmscout@@@osmscout@@@std@@@std@@XZ) referenced in function "public: void __cdecl osmscout::LabelLayouter<struct osmscout::MapPainterSVG::NativeGlyph,class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> >,class osmscout::MapPainterSVG>::DrawLabels<class osmscout::MapPainterSVG>(class osmscout::Projection const &,class osmscout::MapParameter const &,class osmscout::MapPainterSVG *)" (??$DrawLabels@VMapPainterSVG@osmscout@@@?$LabelLayouter@UNativeGlyph@MapPainterSVG@osmscout@@V?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@V23@@osmscout@@QEAAXAEBVProjection@1@AEBVMapParameter@1@PEAVMapPainterSVG@1@@Z)
C:\WINDOWS\MapPainterSVG.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl osmscout::LabelLayouter<struct osmscout::MapPainterSVG::NativeGlyph,class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> >,class osmscout::MapPainterSVG>::~LabelLayouter<struct osmscout::MapPainterSVG::NativeGlyph,class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> >,class osmscout::MapPainterSVG>(void)" (__imp_??1?$LabelLayouter@UNativeGlyph@MapPainterSVG@osmscout@@V?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@V23@@osmscout@@QEAA@XZ) referenced in function "public: virtual __cdecl osmscout::MapPainterSVG::~MapPainterSVG(void)" (??1MapPainterSVG@osmscout@@UEAA@XZ)
C:\WINDOWS\libosmscout-map-svg\osmscout_map_svgd.dll : fatal error LNK1120: 11 unresolved externals
```
Did you have idea how to fix it?

**Comment by Karry** [comment]
MSVC linker issue was simple... I can't use `OSMSCOUT_MAP_API` in templated classes. Anyway, it is possible to build DirectX renderer, but necessary methods are empty...

**Comment by Framstag** [comment]
Fine. I still plan to take a look at it next week (I have holiday then).

**Pull request merged**
