### PR TITLE
Raise the FileWriter::MAX_NODES limit to 0x03FFFFFF (26 bits) to allo…

### PR DESCRIPTION
**Pull request by vyskocil**
…w more nodes in large multi-polygon like country borders

### CODE REVIEW

**Comment by Framstag** [comment]
Hello Vladimir, doesn't the FileScanner needs a change, too? IT has to load the data back you have written.

**Comment by Framstag** [comment]
See FileScanner::Read(). It reads only 3 bytes for the length. The code thus does not crash but it would not read all the coordinates because the nodeCount is smaller than it should?

Interesting enough it should crash if a data file is read sequentially because it would interpret the rest of the coordinates not read as begin of the next data entry...hmmm...strange.

**Comment by Framstag** [comment]
OK :-) I wait for the central builds to finish and will then merge the request

**Comment by Karry** [comment]
Looks good. But it seems to me that this change is not backward compatible - this code will not work with current databases. We should increase database version.

**Comment by Framstag** [comment]
Right.

**Pull request merged**
