### PR TITLE
print memory allocation statistics in PerformanceTest…

### PR DESCRIPTION
**Pull request by Karry**
optionally store memory profiler snapshots (using Gperftools)

Cmake build now detects optional dependency - Gperftools and link PerformanceTest with it.
If Gperf tools are available, last optional argument of PerformanceTest can define heap
profiler prefix.

Besides heap profiler snapshots, PerformanceTest summary now prints maximum and average
allocated memory for one tile. Statistics is calculated for each zoom level separately.
This information is obtained from mallinfo() or tc_mallinfo() function.

==========
Level: 0
 Used memory: max: 12.4019 MiB avg: 12.4019 MiB
 Tot. data  : nodes: 0 way: 0 areas: 0
 Avg. data  : nodes: 0 way: 0 areas: 0
 DB         : total: 49.2934 min: 49.2934 avg: 49.2934 max: 49.2934
 Map        : total: 828.595 min: 828.595 avg: 828.595 max: 828.595
Level: 1
 Used memory: max: 15.0057 MiB avg: 15.0057 MiB
 Tot. data  : nodes: 0 way: 229 areas: 0
 Avg. data  : nodes: 0 way: 229 areas: 0
 DB         : total: 80.4045 min: 80.4045 avg: 80.4045 max: 80.4045
 Map        : total: 5.21047 min: 5.21047 avg: 5.21047 max: 5.21047

### CODE REVIEW

**Comment by Framstag** [comment]
This broke the following travis build (other builds broke because of other, unknown errror):

https://travis-ci.org/Framstag/libosmscout/jobs/133964762

/Users/travis/build/Framstag/libosmscout/Demos/src/PerformanceTest.cpp:384:38: error: invalid use of incomplete type 'mallinfo'

        struct mallinfo alloc_info = mallinfo();

                                     ^~~~~~~~~~

/Users/travis/build/Framstag/libosmscout/Demos/src/PerformanceTest.cpp:384:16: note: forward declaration of 'mallinfo'

        struct mallinfo alloc_info = mallinfo();

               ^

/Users/travis/build/Framstag/libosmscout/Demos/src/PerformanceTest.cpp:384:25: error: variable has incomplete type 'struct mallinfo'

        struct mallinfo alloc_info = mallinfo();

                        ^

/Users/travis/build/Framstag/libosmscout/Demos/src/PerformanceTest.cpp:384:16: note: forward declaration of 'mallinfo'

        struct mallinfo alloc_info = mallinfo();

Your pull request looks definitely interesting. Could you try to fix it? Looks like some include is missing under Mac OS X.

**Comment by Karry** [comment]
It seems that <malloc.h> import is missing when GPERFTOOLS are not available...

**Comment by Framstag** [comment]
Ye,s but that header does not seem to exist under Mac OS X (yes, I love it :-)).

```
[ 84%] Building CXX object Demos/CMakeFiles/PerformanceTest.dir/src/PerformanceTest.cpp.o

/Users/travis/build/Framstag/libosmscout/Demos/src/PerformanceTest.cpp:44:10: fatal error: 'malloc.h' file not found

#include <malloc.h>
```

**Comment by Karry** [comment]
It seems that mallinfo function is not available with Clang Xcode. Or I'm missed something? But should be still possible to use Gperftools and its tcmalloc on Mac OS, so memory measurement should be available on all platforms. I added check for availability of mallinfo function to cmake and add extra conditions to source code.

**Comment by Karry** [comment]
Tim, are you able to test combination of Clang + Gperftools on MacOS?

**Comment by Framstag** [comment]
Sorry no. I do not have a Mac myself. That is one of the reasons I set up Travis and Appveyor builds. The Mac OS support was done by Vladimir.

**Pull request merged**
