### PR TITLE
fix width of the route

### PR DESCRIPTION
**Pull request by janbar**

### CODE REVIEW

**Comment by janbar** [comment]
The width of the route is sized to 6 meters for high zoom.
image

**Comment by Framstag** [comment]
For style sheet changes I assign @Karry as reviewer, since he will make use of our changes, too. You can assign him directly for further changes. I can live with the results as long as you two agree (though I loved my color scheme :-()

**Comment by janbar** [comment]
Oki. Also this change doesn't update the color. The screenshot is only a sample to show you the width of the route on high zoom.

**Review by Karry — APPROVED** [review]
LGTM. It makes sense to keep _route width similar to street/way under it.

**Comment by Karry** [comment]
Btw, I'm not using upstream stylesheets in my app, but slightly modified versions, with different color palette and few small modifications. But with new "module" support, I will try to sync them...

**Pull request merged**
