### PR TITLE
GHA: Use Ninja with CMake in msys2

### PR DESCRIPTION
**Pull request by Biswa96**
Ninja is faster than make in msys2

### CODE REVIEW

**Comment by Framstag** [comment]
Sorry for the late reply. I just have seen, that I need to activate the builds manually, since this is the first pull request from you.

Patch looks good to me, we'll see, if the builds run.

Thanks for this pull request!

**Comment by Framstag** [comment]
I love windows. Seem like things work with ninja in principle, but we now get a compiler error (which AFAIK we already had before) we did not have before. Is this something you can reproduce or even fix? It can (it likely is) be unrelated to our changes, but a fix would be helpful to do not have an e´increased count of failing builds (since I have no time to look at it myself).

**Comment by Biswa96** [comment]
Done.

**Comment by Framstag** [comment]
Perfect. I love to see more pull requests :-)

**Pull request merged**
