### PR TITLE
Add binding for MATLAB

### PR DESCRIPTION
**Pull request by OgreTransporter**
Lookup and map drawing functions for MATLAB/Simulink

### CODE REVIEW

**Comment by Karry** [comment]
Hi. I am just curious - what is the main usage of OSM Scout functions in Matlab? I have no problem with your changes and I definitely like your GeoCoord improvements. But last word will have Tim of course.

**Comment by Framstag** [comment]
I have not yet pushed this patch (which is OK for me), because it looked like it broke the appveyor build. I asked OgreTransporter to take a look (since he also offered the cmake files initially) but he has not yet responded.

As far as I understood he use the code to enhance geo located information already available with OSM specific data.

**Comment by OgreTransporter** [comment]
> what is the main usage of OSM Scout functions in Matlab?
I need to draw an OSM map in a MATLAB figure and get information on various GPS positions.

**Comment by Framstag** [comment]
Manually merged.

**Pull request closed without merging**
