### PR TITLE
update C++ standard to 17

### PR DESCRIPTION
**Pull request by Karry**
Lets see which CI pipelines fails... and I am running docker builds locally...

### CODE REVIEW

**Comment by Karry** [comment]
Static import tool build fails on Travis: https://travis-ci.org/github/Framstag/libosmscout/jobs/671194167 I will take a look on that..

**Comment by Framstag** [comment]
Looks like the travis build is using gcc 4.8.4, likely does not know anything about c++17. The other Linux cmake build uses gcc 7.4.0. Hmm, does one of the dependencies not installed for the static installer pull a newer gcc?

**Comment by Framstag** [comment]
No the ubuntu release versions are different...

**Comment by Framstag** [comment]
This is as designed. The .travis.yml states, that the static build does not work with Xenial or Bionic.

Hmm, might building static libraries with meson worth a try?

**Comment by Karry** [comment]
It seems `FindLibXml2.cmake` don't list all required libraries for static linking. Here is workaround: https://github.com/Framstag/libosmscout/pull/838/commits/424aca1e3019fe06df0bab7323836f527927ff7a

**Comment by Karry** [comment]
Downside of this workaround is that multiple libraries are linked dynamically :-/ 
```
	linux-vdso.so.1 (0x00007fff78588000)
	libicuuc.so.60 => /usr/lib/x86_64-linux-gnu/libicuuc.so.60 (0x00007fb78eeb9000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fb78ec9c000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007fb78ea76000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fb78e857000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fb78e4b9000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb78e0c8000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fb78fa2a000)
	libicudata.so.60 => /usr/lib/x86_64-linux-gnu/libicudata.so.60 (0x00007fb78c51f000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fb78c31b000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fb78bf92000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fb78bd7a000)
```

**Comment by Framstag** [comment]
The MSVC2015 builds fail because the compiler does not support c++17 (at least meson thinks so). Look like we should look for a newer version of the compiler - at least if we actively start using C++17 features.

Static build: The aim of the static build was, to build a dependency-less version of the Importer. Having dependencies on dynamic libraries is thus a problem. Though you likely cannot avoid linking libc and it companion libraries. So this likely leaves libz and liblzma?

**Comment by Framstag** [comment]
Btw ´, in meson it is:

```
meson setup --default-library static --buildtype debugoptimized static
cd static
ninja
```

However the Importer also has dynamic library dependencies - for most of the though there is no *.a file on my disk.

```
$ ldd Import/Import 
	linux-vdso.so.1 (0x00007fff70f18000)
	libmarisa.so.0 => /usr/lib/libmarisa.so.0 (0x00007f8519000000)
	libxml2.so.2 => /usr/lib/libxml2.so.2 (0x00007f8518e9a000)
	libprotobuf.so.22 => /usr/lib/libprotobuf.so.22 (0x00007f8518b72000)
	libz.so.1 => /usr/lib/libz.so.1 (0x00007f8518b58000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f851896f000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007f8518829000)
	libgomp.so.1 => /usr/lib/libgomp.so.1 (0x00007f85187ee000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f85187d4000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f85187b2000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f85185ec000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f8519289000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f85185e7000)
	libicuuc.so.65 => /usr/lib/libicuuc.so.65 (0x00007f8518405000)
	liblzma.so.5 => /usr/lib/liblzma.so.5 (0x00007f85183db000)
	libicudata.so.65 => /usr/lib/libicudata.so.65 (0x00007f851692a000)
```

**Comment by Karry** [comment]
Import is static now. It just have runtime dependency on glibc. Take a look to https://github.com/Framstag/libosmscout/pull/838/commits/4eadec1e62bde3d1550d55cf1c39d059df5eb30c for details ;-)

**Pull request merged**
