### PR TITLE
new PostalCode feature

### PR DESCRIPTION
**Pull request by aquiles2k**
*added basic postal code to nodes in the location index through a new PostalCode feature for map.ost
*extended location lookup demo to display the postal code in results

### CODE REVIEW

**Comment by Karry** [comment]
If I understand changes correctly, when one RegionLocation contains more RegionAddress with same postalCode, location index stores postalCodes multiple times. Right? How much bigger is location index now?

**Comment by aquiles2k** [comment]
No, i'm just appending myself to the existing logic.

The multi insertion was already there. See comment in AddAddressNodeToRegion:

> It is possible that the address is already available at the location. We add it anyway. It is possible that multiple nodes share the same address (because their are in the	same building) and an area (the building) might hold the address, too.

My old Berlin import with nothing changed:

  

> Mandatory files:
>    File areaarea.idx: 314.7 KiB
>    File areanode.idx: 1.3 MiB
>    File areas.dat: 12.9 MiB
>    File areaway.idx: 211.3 KiB
>    File bounding.dat: 14 B
>    File intersections.dat: 2.4 MiB
>    File intersections.idx: 749.0 KiB
>    File location.idx: 2.1 MiB
>    File nodes.dat: 4.6 MiB
>    File router.dat: 8.2 MiB
>    File router.idx: 750.0 KiB
>    File router2.dat: 543 B
>    File types.dat: 25.5 KiB
>    File water.idx: 82.6 KiB
>    File ways.dat: 4.4 MiB
>    => 38.0 MiB
>    Optional files:
>    File areasopt.dat: 67.6 KiB
>    File waysopt.dat: 121.4 KiB
>    => 189.0 KiB
>    Import OK!
> 

Now with my changes:

> 328081 nodes analyzed, 310106 addresses founds, 13169 POIs founds, 320779 postal codes found

> Mandatory files:
>    File areaarea.idx: 314.7 KiB
>    File areanode.idx: 1.3 MiB
>    File areas.dat: 12.9 MiB
>    File areaway.idx: 211.3 KiB
>    File bounding.dat: 14 B
>    File intersections.dat: 2.4 MiB
>    File intersections.idx: 749.0 KiB
>    File location.idx: 3.8 MiB
>    File nodes.dat: 6.5 MiB
>    File router.dat: 8.2 MiB
>    File router.idx: 750.0 KiB
>    File router2.dat: 543 B
>    File types.dat: 27.0 KiB
>    File water.idx: 82.6 KiB
>    File ways.dat: 4.4 MiB
>    => 41.6 MiB
>    Optional files:
>    File areasopt.dat: 67.6 KiB
>    File waysopt.dat: 121.4 KiB
>    => 189.0 KiB
>    Import OK!

**Comment by Framstag** [comment]
That looks good for me, so I merge it :-) Thanks. From some initial scanning of code: For the postalCode it does only evaluate the information at the object itself, it does not evaluate any boundary relation as a fallback? So this is something that is still on your list?

**Comment by Framstag** [comment]
This also changes the file format, right?

**Comment by aquiles2k** [comment]
Im writing to the location index in WriteAddressDataEntry() and to nodeaddress.dat in NodeLocationProcessorFilter::Process() so i guess yes :)

**Comment by aquiles2k** [comment]
Yes only all nodes with addr:postcode for now. There also seem to be a lot of areas with this tag so i might look at this next. The boundary relation fallback is still still on my to look at list but right now im happy that this basic thing is working.

**Pull request merged**
