### PR TITLE
A number of clang tidy fixes

### PR DESCRIPTION
**Pull request by Framstag**

### CODE REVIEW

**Comment by Karry** [comment]
Please wait with this merge request after my "route-rendering" :-) I hope that it will be ready soon and I am worry that this one will cause many conflicts...

**Comment by Framstag** [comment]
> Please wait with this merge request after my "route-rendering" :-) I hope that it will be ready soon and I am worry that this one will cause many conflicts...

OK

**Comment by Framstag** [comment]
Route rendering is merged, will you take over or should I do the merges?

**Comment by Karry** [comment]
I just made rebase and resolve two conflicting files ;-)

**Pull request merged**
