### PR TITLE
try to fix Travis CI build of Cairo backend on Mac

### PR DESCRIPTION
**Pull request by Karry**

### CODE REVIEW

**Comment by Karry** [comment]
`cairo.h` include seems to be fixed, but now it is complaining about `<pango/pangocairo.h>` :-(

**Comment by Framstag** [comment]
I'll take a look...

**Comment by Framstag** [comment]
Looks like you need a
```
export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig
```

before a call to 
```
meson debug
```

internally pkg-config is called to get the -I options. Seems like it returns nothing without above export. Looks like something in the brew packages did not change for good.

**Comment by Framstag** [comment]
Do you want to improve the patch or should I try to fix it and commit it?

**Comment by Karry** [comment]
Great catch. It helps!

**Comment by Framstag** [comment]
For this I have a Mac Book Pro. With the same installation on a local device is was simple to found the cause :-)

**Comment by Framstag** [comment]
Thanks for fixing the first part!

**Comment by Karry** [comment]
Little bit expensive testing device :-) You are welcome!

**Pull request merged**
