### PR TITLE
Static importer

### PR DESCRIPTION
**Pull request by Karry**

### CODE REVIEW

**Comment by Karry** [comment]
damn, it is still failing... with different error now:
```
/usr/lib/x86_64-linux-gnu/libc.a(abort.o): In function `abort':
(.text+0x1e4): undefined reference to `__sigaction'
```

**Comment by Framstag** [comment]
How does this correlate with #917 ? Should I merge both?

**Comment by Karry** [comment]
no, I will close this one. @OgreTransporter pick up change to his merge request...

**Comment by OgreTransporter** [comment]
@Karry I had the same error. The switch `-static` solved the problem for me (42b12b53dfcfde999ed12a79041dd29be31ebdfb).

**Pull request closed without merging**
