### PR TITLE
add the color feature to custom poi types

### PR DESCRIPTION
**Pull request by janbar**
Allows to set the preferred color for an overlay object.
Then if the type config is set accordingly as follows, the color will be applied.

Config in oss stylesheet:

[TYPE _custom] WAY { preferColorFeature: true; color: @trackColor; }

### CODE REVIEW

**Comment by janbar** [comment]
@Karry, I proposed a change to add the color feature to the registered custom poi type.

**Review by Karry — APPROVED** [review]
LGTM

**Comment by Karry** [comment]
I like the idea of custom waypoint and track colors, I need to extend UI in my app to allow that :-) Moreover I will need ability to export custom color to gpx...

**Comment by janbar** [comment]
@Karry, cf PR #1067 as purpose for adding extensions element

**Pull request merged**
