### PR TITLE
Import script for Windows

### PR DESCRIPTION
**Pull request by DerKleinePunk**
Import Script create with rinigus

### CODE REVIEW

**Comment by rinigus** [comment]
This script is required to make PR https://github.com/Framstag/libosmscout/pull/163 work. My PR does not include the script, just the both PRs have to be merged to make it all work.

An example packages with the released import tool incorporating this script are at https://github.com/rinigus/libosmscout/releases/tag/0.0.git.20161128.2

@DerKleinePunk, thank you very much for making the script!

**Comment by rinigus** [comment]
@DerKleinePunk, Is there any reason you closed it and deleted the branch? Or was it an accident?

Note that its not merged yet. 

If you wish, I could push it via my PR, but it was OK as it was, I think.

**Comment by DerKleinePunk** [comment]
Hello rinigus,

Sorry i try to remerge change from tim.
and delete make new branch for build with vs2015

i've think tim has merged.

sorry i'm new on github.

I think i rebuild the branch

Der kleine Punk

Am 04.12.2016 um 18:53 schrieb rinigus:

**Comment by rinigus** [comment]
Evening, 

no worries. You know what, I think I can put your changes with your name attached via my pull request. I'll try it a bit later and will let you know how it went.

These changes are rather large and Tim would need to read up on them. That's why it takes time :)

**Comment by DerKleinePunk** [comment]
Why ? the branch is back on my repos

Am 04.12.2016 um 20:31 schrieb rinigus:

**Comment by rinigus** [comment]
cool! then you have to open a new pull request from that branch, this pr was closed when you closed your branch.

**Pull request closed without merging**
