### PR TITLE
Try to fix the contour label visibility problem as described in issue…

### PR DESCRIPTION
**Pull request by Framstag**
… #1220

* Improved spacing values and fix projection calculation.

### CODE REVIEW

**Comment by Karry** [comment]
Nice. It is better. But still, some street names visible previously are hidden. Seems that short streets, like https://www.openstreetmap.org/way/22561047#map=19/43.62046/6.97074 are problematic.

**Comment by Framstag** [comment]
@Karry The problem is, that the current (new) implementation only evaluates labelSpaces which is now a correct but still rather high value. This result in the requirement, that the way has to be rather long to get a label shown. It should take labelOffset also into account, which should then be a smaller value.
I'm also not yet satisfied with the overall result, I would like the label count to be a sequence of 1,3,7...labels to have a smoother effect on zooming in and out (the overall number of labels would be 1+2+4+8+16....). However that is currently not yet the implementation.

I'll merge this one in the evening and will take a look for an overall improvement in a later separate pull request.

**Comment by Karry** [comment]
For shorter way, I would rather ignore spacing (break the rules), instead of not showing label at all.

**Comment by Karry** [comment]
I tried to use this modification:
```
countLabels=std::max(size_t(1), size_t(pow(2.0,floor(log2(double(countLabels))))));
```
on line 792, as exception for short ways, but the ["Rue Pasteur" label](https://www.openstreetmap.org/way/22561047#map=19/43.62046/6.97074) was filtered out because of variance test (line 801). It will be hard to find some heuristics for label placement to fill requirements:

 - show at least some label even for shorter ways
 - make it stable to avoid label movements during zooming

**Pull request merged**
