### PR TITLE
parser oss: check deref nullptr, therefore revert commit cf8d1c746aa5…

### PR DESCRIPTION
**Pull request by janbar**
For instance, all errors should be discarded when state is false. So here the commit implements all check or flow to avoid deref nullptr.

### CODE REVIEW

**Comment by janbar** [comment]
@Framstag , this is the good fix. The style parsing works great now and there is no longer side effect.

**Comment by Karry** [comment]
Hi @janbar , this change breaks rendering of `highway_path` with https://github.com/Karry/osmscout-sailfish/blob/master/stylesheets/outdoor.oss stylesheet. There is this warning in the log:
```
Line style for way XXX of type highway_path results in empty mainSlotWidth
```

Do you have idea what is broken? I don't review your changes yet. Just done some git archeology :-)

**Comment by janbar** [comment]
@Karry, trying and get the same, but don't know the root cause.

Capture d’écran du 2024-09-07 11-23-27

In the example above, changing "DisplayWidth" to 0mm, the warning disappears. Any idea ?

**Comment by janbar** [comment]
Same case here:
Capture d’écran du 2024-09-07 12-31-21

**Comment by janbar** [comment]
@Karry, I found an issue with the color value parsing. I prepare a new PR.

**Comment by janbar** [comment]
I pushed fixes with the PR #1597

**Comment by Karry** [comment]
Thank you, it fixes the issue.

**Pull request merged**
