### PR TITLE
Fatal signal 11 (SIGSEGV) is comming back using shared pointers in on…

### PR DESCRIPTION
**Pull request by janbar**
…SearchResult()

The issue occurs at least from ndk18b up to ndk21e.
We needs to pass c pointers to std::sort() to workaround the issue on aarch android platforms.

```
03-31 19:19:27.261 22904 22927 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x29a2f4ae1310d5 in tid 22927 (qtMainLoopThrea), pid 22904 (ub.janbar.osmin)
03-31 19:19:27.547 23016 23016 F DEBUG   : pid: 22904, tid: 22927, name: qtMainLoopThrea  >>> io.github.janbar.osmin <<<
03-31 19:19:27.554 23016 23016 F DEBUG   :       #00 pc 00000000002c6950  /data/app/io.github.janbar.osmin-CG5v6nClwcbIN2J58KOFNw==/lib/arm64/libosmin.so (BuildId: d98c0463527c8a38af78e04cff0c1dde92785c8b)
03-31 19:19:27.554 23016 23016 F DEBUG   :       #01 pc 00000000002c97b8  /data/app/io.github.janbar.osmin-CG5v6nClwcbIN2J58KOFNw==/lib/arm64/libosmin.so (BuildId: d98c0463527c8a38af78e04cff0c1dde92785c8b)
03-31 19:19:27.554 23016 23016 F DEBUG   :       #02 pc 00000000002c9680  /data/app/io.github.janbar.osmin-CG5v6nClwcbIN2J58KOFNw==/lib/arm64/libosmin.so (BuildId: d98c0463527c8a38af78e04cff0c1dde92785c8b)
03-31 19:19:27.554 23016 23016 F DEBUG   :       #03 pc 00000000002c5218  /data/app/io.github.janbar.osmin-CG5v6nClwcbIN2J58KOFNw==/lib/arm64/libosmin.so (osmscout::LocationListModel::onSearchResult(QString, QList<osms>
03-31 19:19:27.554 23016 23016 F DEBUG   :       #04 pc 00000000002c8a30  /data/app/io.github.janbar.osmin-CG5v6nClwcbIN2J58KOFNw==/lib/arm64/libosmin.so (_ZN9QtPrivate11FunctorCallINS_11IndexesListIJLi0ELi1EEEENS_4Lis>
03-31 19:19:27.554 23016 23016 F DEBUG   :       #05 pc 00000000002aeb74  /data/app/io.github.janbar.osmin-CG5v6nClwcbIN2J58KOFNw==/lib/arm64/libQt5Core.so (QObject::event(QEvent*)+540)
03-31 19:19:27.554 23016 23016 F DEBUG   :       #06 pc 0000000000281248  /data/app/io.github.janbar.osmin-CG5v6nClwcbIN2J58KOFNw==/lib/arm64/libQt5Core.so (QCoreApplicationPrivate::notify_helper(QObject*, QEvent*)+408)
03-31 19:19:27.554 23016 23016 F DEBUG   :       #07 pc 0000000000280d94  /data/app/io.github.janbar.osmin-CG5v6nClwcbIN2J58KOFNw==/lib/arm64/libQt5Core.so (QCoreApplication::notify(QObject*, QEvent*)+104)
03-31 19:19:27.554 23016 23016 F DEBUG   :       #08 pc 0000000000280cb4  /data/app/io.github.janbar.osmin-CG5v6nClwcbIN2J58KOFNw==/lib/arm64/libQt5Core.so (QCoreApplication::notifyInternal2(QObject*, QEvent*)+264)
03-31 19:19:27.554 23016 23016 F DEBUG   :       #09 pc 0000000000281e68  /data/app/io.github.janbar.osmin-CG5v6nClwcbIN2J58KOFNw==/lib/arm64/libQt5Core.so (QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThr>
03-31 19:19:27.554 23016 23016 F DEBUG   :       #10 pc 00000000002da788  /data/app/io.github.janbar.osmin-CG5v6nClwcbIN2J58KOFNw==/lib/arm64/libQt5Core.so (QEventDispatcherUNIX::processEvents(QFlags<QEventLoop::Proces>
03-31 19:19:27.554 23016 23016 F DEBUG   :       #11 pc 0000000000056060  /data/data/io.github.janbar.osmin/qt-reserved-files/plugins/platforms/android/libqtforandroid.so
03-31 19:19:28.464 23016 23016 I chatty  : uid=10253(io.github.janbar.osmin) crash_dump64 identical 2 lines
```

### CODE REVIEW

**Comment by janbar** [comment]
@karry, devil is coming back

**Comment by janbar** [comment]
Reviewing the spec for std::sort( RandomIt, RamdomIt, compare ), they explain the following:
- RandomIt must meet the requirements of ValueSwappable and LegacyRandomAccessIterator.
- The type of dereferenced RandomIt must meet the requirements of MoveAssignable and MoveConstructible.
A pointer (long) matches those last requirements. To be checked for shared_ptr, or previously QObject ...

**Comment by Karry** [comment]
It is frustrating. Btw, can you write some tutorial howto setup development environment for building and testing Osmin for Android please? Or just link some tutorial that you are using...

Regarding to your note about requirements of `std::sort` to use with copyable and movable types, you are right. But `shared_ptr` should comply of these requirements without requiring it from inner type... Anyway, looking to `LocationEntry`, it is not compliant with "rule of five" - copy assignment operator and movable contructor / operator are missing... It may be the root of the issues. Compiler then may have invalid assumptions and break something. These rules are not easy to remember and it is recommended to always define all five resource management methods explicitly (or none). I created MR for that: https://github.com/Framstag/libosmscout/pull/1041

Regarding your patch, I would like to avoid raw pointers...

**Comment by janbar** [comment]
@Karry, I documented in the osmin sources how to build the android apk. Prefer to use Ubuntu or a Linux host to build. Scripts and readmes are in the folder "android". First you need to install some tools:
- Create the folder in your build host where you install shared tools: it could be "/home/shared" like me.
- Create the folder "/home/shared/Android" where you will deploy the ndks i.e "android-ndk-r18b"
- Download the Android studio: https://developer.android.com/studio
- Install the Android studio in "/home/shared/android-studio". It will contains required sdk for devices (24, 26)
- Download the android ndk18b: https://dl.google.com/android/repository/android-ndk-r18b-linux-x86_64.zip
- Unzip the ndk into the folder you created before: "/home/shared/Android/"
At this point you need to start android-studio (/home/shared/android-studio/bin/studio.sh) to configure/install sdk you need for your build.

My public email is jlbarriere68@gmail.com. It could be more easy to explain you the next stage. After you have deployed tools ans sdk with android studio, you will need only your terminal console to build the app.

**Comment by Framstag** [comment]
Please give me a sign, if I should merge. Sounds like you are both still looking for a better solution?

**Comment by janbar** [comment]
@Karry, I merged the dev branch of my app into master branch. So now you can build it from the master branch. The fork of libosmscout is up to date with upstream (only 1 commit applied over to fix the build of libxml2), and without this patch. Searching "gle" with Germany database crash the app.

**Comment by janbar** [comment]
I close this, because resolved by #1047

**Pull request closed without merging**
