### PR TITLE
Implementation of MODULE statement to the OSS files.

### PR DESCRIPTION
**Pull request by Framstag**
Adding some modules for testing (further modularisation likely makes sense, if the feature completely works)

### CODE REVIEW

**Review by Karry — APPROVED** [review]
I like it :-)

**Comment by Karry** [comment]
Ups, it seems that this change breaks area rendering with standard stylesheet and zoom level >= 19

**Comment by Framstag** [comment]
Hmmm, how? Any idea?

**Comment by Karry** [comment]
Not yet. I am debugging broken label layouter. I introduced bug with my latest refactoring :-/

**Comment by Framstag** [comment]
> Not yet. I am debugging broken label layouter. I introduced bug with my latest refactoring :-/

The changes also may subtly change initialization of StyleConfig. I removed a reset() method which would have effect if the same StyleConfig is loaded again (but I did not see such code). Also Postprocess() is called multiple times  while it might not have an effect, this is something that should be changed (by adding another parameter to LoadContent (subModule true/false).

**Comment by Karry** [comment]
I don't see any obvious bug, but difference is visible even when you run `OSTAndOSSCheck` tool with `--analyze` argument, on style with "modules" and without it...

```
./Tests/OSTAndOSSCheck --analyze ../stylesheets/map.ost ../stylesheets/standard.oss
```
Screenshot_20220418_231958

> ... Also Postprocess() is called multiple times while it might not have an effect

I am not so sure, there is computed `size_t maxLevel=0;`, and that may be the issue... It should be computed just once I guess.

**Pull request merged**
