### PR TITLE
Navigation

### PR DESCRIPTION
**Pull request by Karry**
Hi Tim. 

This merge request is little bit bigger, but it is more or less limited to routing and navigation. It is using your concept of agents, but I rewrote most of agents and used messages.

main agents:
 - **DataAgent** - loads routable objects when there is data request message
 - **PositionAgent** - pin location to route or nearest routable object, when distance from the route is too high. It tries to estimate position in tunnel. But it is not tested! Also evaluate position state (NoGpsSignal, OnRoute, OffRoute, EstimateInTunnel).
 - **RouteInstructionAgent** - evaluate following route instructions and next route instruction

other changes:
 - Qt/QML navigation was updated to new API
 - Qt route instructions now using `RouteDescriptionPostprocessor` (renamed `RouteDescriptionGenerator`). It is removing some duplicate code...

future work:
 - solve corner cases
 - improve route instructions
 - test position estimate in tunnels
 - evaluate lanes, vehicle speed...
 - improve routing to take starting bearing into account - it will improve re-routing experience

### CODE REVIEW

**Comment by Framstag** [comment]
The patch is too big to make any judgment, so I'll pass it anyway. I have not seen anything forbidden and most changes are just moving things around, adapting code etc to give things a better interface an make nicer code (and there is likely new functionality there :-)) There are however some build errors under Windows that should be taken care of before.

**Comment by Karry** [comment]
Hi. I am trying to fix windows build in other merge requests. When it will be green, I will rebase this merge request on master then...

**Comment by Framstag** [comment]
OK

**Comment by Framstag** [comment]
Just to be sure, I'm waiting for your "go merge" on this :-)

**Comment by Karry** [comment]
Ok, you can merge it, AppVeyor build is green :-) I will create new merge requests with follow-up navigation changes...

**Pull request merged**
