### PR TITLE
add support for label and icon padding

### PR DESCRIPTION
**Pull request by Karry**
Add support for label and icon padding (again). I just removed `sameLabelSpace` option, because it would be hard to implement with current layouter.

### CODE REVIEW

**Comment by Framstag** [comment]
Hmm, this seam to create two different build errors? Though I did not see a change that would have triggered that!?

**Comment by Karry** [comment]
It seems that Qt translation files was removed by accident. There is some cmake / lupdate bug that delete them sometimes...

I will restore it...

**Comment by Framstag** [comment]
Thanks!

**Comment by Karry** [comment]
Missing translations files seems not to be the issue. But broken Qt installation in AppVeyor / msys2 instance...

```
C:/msys64/mingw64/bin/lupdate.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory
```

**Comment by Framstag** [comment]
Hmmm, I rebuild everything. Lets see if it persists. The Qt5 package itself is the same as always.

**Comment by Framstag** [comment]
Push it anyway...

**Pull request merged**
