### PR TITLE
fix DirectX character encoding

### PR DESCRIPTION
**Pull request by Karry**
try to fix https://github.com/Framstag/libosmscout/issues/962

@ghpl210312 may I ask for review please? I have no windows machine.

### CODE REVIEW

**Comment by Framstag** [comment]
@ghpl210312

As you can see from the CI/CD builds, you should be able to retrieve the patch by:

```
git clone -q https://github.com/Framstag/libosmscout.git C:\projects\libosmscout
git fetch -q origin +refs/pull/1012/merge:
git checkout -qf FETCH_HEAD
Restoring build cache
```

**Comment by Karry** [comment]
No response from @ghpl210312 :-( I would merge it @Framstag , builds are green and this change should fix described issue...

**Comment by ghpl210312** [comment]
Hi guys,
I am really sorry, but I my work keeps me quite busy at the moment.
I tested it only with my version, but these lines from MapPainterDirectX do the same:

#ifdef MBUC
    std::wstring wText = UTF8StringToWString(text);
    for (size_t ch = 0; ch < wText.length(); ch++) {
      std::wstring sample = wText.substr(ch,1);
#else
    for (size_t ch = 0; ch < text.length(); ch++) {
      std::string sample = text.substr(ch,1);
#endif

**Comment by Framstag** [comment]
I'm not sure that this is the optimal solution, but I see that it might improve the situation. I in principle can test it myself but also lack time, Thus I'll merge it now :-)

**Pull request merged**
